// <auto-generated />
using System;
using ItaLog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItaLog.Data.Migrations
{
    [DbContext(typeof(ItaLogContext))]
    partial class ItaLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItaLog.Domain.Models.ApiRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ApiRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("ItaLog.Domain.Models.ApiUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("UserToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ApiUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 68, DateTimeKind.Local).AddTicks(8403),
                            Email = "admin@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(1965),
                            Name = "Admin",
                            NormalizedUserName = "ADMIN@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "admin@contato.com",
                            UserToken = new Guid("63c7a51a-06d6-4819-b690-d0ca40a90103")
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2603),
                            Email = "itau@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2615),
                            Name = "Itau",
                            NormalizedUserName = "ITAU@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "itau@contato.com",
                            UserToken = new Guid("ca32612a-ab36-4acf-8610-001cfd9f4cc4")
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2637),
                            Email = "afonso@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2639),
                            Name = "Afonso",
                            NormalizedUserName = "AFONSO@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "afonso@contato.com",
                            UserToken = new Guid("2fb55a27-23f0-4d4f-aecb-a280010e8d57")
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2641),
                            Email = "andre@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2642),
                            Name = "André",
                            NormalizedUserName = "ANDRE@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "andre@contato.com",
                            UserToken = new Guid("56e9e440-0bfe-4105-aa9d-a50084aae2e3")
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2645),
                            Email = "brunna@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2646),
                            Name = "Brunna",
                            NormalizedUserName = "BRUNNA@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "brunna@contato.com",
                            UserToken = new Guid("56f88cc2-acc1-4a14-821f-f7b7058d1c06")
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2648),
                            Email = "bruno@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2649),
                            Name = "Bruno",
                            NormalizedUserName = "BRUNO@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "bruno@contato.com",
                            UserToken = new Guid("19137a30-888e-49ba-a60d-2dd5c03c8227")
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2652),
                            Email = "carlos@contato.com",
                            EmailConfirmed = true,
                            LastUpdateDate = new DateTime(2020, 4, 25, 18, 26, 11, 69, DateTimeKind.Local).AddTicks(2652),
                            Name = "Carlos",
                            NormalizedUserName = "CARLOS@CONTATO.COM",
                            Password = "AQAAAAEAACcQAAAAENiU++GjfU7q1nAIgwulJmL319Hj8DHBCiiag198T1yUIOSQusFnjpQDjdYZuxjCPw==",
                            UserName = "carlos@contato.com",
                            UserToken = new Guid("7eb7c1bd-9e17-4b62-bfa1-3485054e04d9")
                        });
                });

            modelBuilder.Entity("ItaLog.Domain.Models.ApiUserRole", b =>
                {
                    b.Property<int>("ApiUserId")
                        .HasColumnType("int");

                    b.Property<int>("ApiRoleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ApiUserId", "ApiRoleId");

                    b.HasIndex("ApiRoleId");

                    b.ToTable("ApiUserRole");
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Environment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Production"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Homologation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Development"
                        });
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<DateTime>("ErrorDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Level");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Debug"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Error"
                        });
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApiUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ApiUserId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("LevelId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("ItaLog.Domain.Models.ApiUserRole", b =>
                {
                    b.HasOne("ItaLog.Domain.Models.ApiRole", "ApiRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApiRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItaLog.Domain.Models.ApiUser", "ApiUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Event", b =>
                {
                    b.HasOne("ItaLog.Domain.Models.Log", "Log")
                        .WithMany("Events")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItaLog.Domain.Models.Log", b =>
                {
                    b.HasOne("ItaLog.Domain.Models.ApiUser", "ApiUser")
                        .WithMany("Logs")
                        .HasForeignKey("ApiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItaLog.Domain.Models.Environment", "Environment")
                        .WithMany("Logs")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItaLog.Domain.Models.Level", "Level")
                        .WithMany("Logs")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
